ALTER TABLE properties
    ALTER COLUMN electricity_unit_price DROP NOT NULL,
    ADD COLUMN IF NOT EXISTS subtitle VARCHAR(200),
    ADD COLUMN IF NOT EXISTS contact_phone VARCHAR(50),
    ADD COLUMN IF NOT EXISTS contact_email VARCHAR(255),
    ADD COLUMN IF NOT EXISTS notes TEXT,
    ADD COLUMN IF NOT EXISTS facilities JSONB;

ALTER TABLE rooms
    ADD COLUMN IF NOT EXISTS size NUMERIC(10,2) CHECK (size >= 0),
    ADD COLUMN IF NOT EXISTS floor VARCHAR(50),
    ADD COLUMN IF NOT EXISTS room_type VARCHAR(50),
    ADD COLUMN IF NOT EXISTS facilities JSONB,
    ADD COLUMN IF NOT EXISTS default_rent_amount INTEGER CHECK (default_rent_amount > 0),
    ADD COLUMN IF NOT EXISTS notes TEXT,
    ADD COLUMN IF NOT EXISTS zone VARCHAR(100);

ALTER TABLE tenants
    ALTER COLUMN email DROP NOT NULL,
    ADD COLUMN IF NOT EXISTS birth_date DATE,
    ADD COLUMN IF NOT EXISTS national_id VARCHAR(50),
    ADD COLUMN IF NOT EXISTS address TEXT,
    ADD COLUMN IF NOT EXISTS occupation VARCHAR(100);

ALTER TABLE leases
    ADD COLUMN IF NOT EXISTS notes TEXT,
    ADD COLUMN IF NOT EXISTS termination_reason TEXT,
    ADD COLUMN IF NOT EXISTS settlement_detail JSONB;
